### PR TITLE
styled the site and added buttons and badges

### PR DESCRIPTION
**Pull request by Ankur9669**
1. Added Buttons and Batches
2. Improved the problem of navbar now it looks good in bigger screens.
3. Converted all the units given in px to rem in documentation.css.
4. Added scrolling functionality in documentation.js.

### CODE REVIEW

**Comment by Naman-Saxena1** [comment]
I checked variable naming, CSS properties, syntax, etc. Code looks fine. In netlify preview, status badge is looking small for large images. Maybe make different sizes of status badges. Everything else looks great.

**Comment by anasm11** [comment]
Great design and the code structure is also good.

**Comment by Ankur9669** [comment]
> I checked variable naming, CSS properties, syntax, etc. Code looks fine. In netlify preview, status badge is looking small for large images. Maybe make different sizes of status badges. Everything else looks great.

They are of differnt sizes, should i make them bigger??

**Comment by Naman-Saxena1** [comment]
> > I checked variable naming, CSS properties, syntax, etc. Code looks fine. In netlify preview, status badge is looking small for large images. Maybe make different sizes of status badges. Everything else looks greatCL > 
> They are of differnt sizes, should i make them bigger??

It is up to you, I made different sizes status in my CL

> > I checked variable naming, CSS properties, syntax, etc. Code looks fine. In netlify preview, status badge is looking small for large images. Maybe make different sizes of status badges. Everything else looks great.
> 
> They are of differnt sizes, should i make them bigger??

It is up to you, I made statuses of different sizes in my CL to match size

**Comment by Ankur9669** [comment]
> 

Ok thanks😊

**Comment by Ankur9669** [comment]
> Great design and the code structure is also good.

Thanks😀

**Pull request merged**
