### PR TITLE
add: added simple inputs

### PR DESCRIPTION
**Pull request by Ankur9669**
image

### CODE REVIEW

**Review by shangkaul — APPROVED** [review]
Looks good  ✅ 
**Tip:** More input styles can be incorporated later (number, date etc.)

**Review by rahulk31 — APPROVED** [review]
Looks good to me. Merge Ready 👍

**Review by mehulsatardekar — APPROVED** [review]
looks good to merge 🚀

**Comment by iamalhera** [comment]
looks good, go ahead to merge

**Comment by Ankur9669** [comment]
> Looks good  ✅ **Tip:** More input styles can be incorporated later (number, date etc.)

Sure buddy

**Pull request merged**
