### PR TITLE
Simplified-grid rating bar

### PR DESCRIPTION
**Pull request by Ankur9669**

### CODE REVIEW

**Comment by AshutoshM29** [comment]
Image from the 30-70 grid is overflowing
edit: rest looks good to me, nice work man!

**Review by Naman-Saxena1 — CHANGES_REQUESTED** [review]
For code, MAs already gave some suggestions. I think you can also make you component example containers and code-snippet container of same width for the consistency. 👍

**Comment by Ankur9669** [comment]
> Image from the 30-70 grid is overflowing edit: rest looks good to me, nice work man!

Thanks a lot, I was missing this part

**Comment by Ankur9669** [comment]
> For code, MAs already gave some suggestions. I think you can also make you component example containers and code-snippet container of same width for the consistency. 👍

Actually, I will remove carbon snippets in the next iteration.

**Pull request merged**
